### ISSUE TITLE
use NVIDIA_DRIVER_CAPABILITIES=all instead of NVIDIA_DRIVER_CAPABILITIES=graphics?

### ISSUE THREAD

**Issue by cbschaff** [afdaniele/x-docker#2]
I can't run pytorch code on a gpu unless more driver capabilities are loaded. Is there a reason you are only using graphics? If not, can you change this to flag to "all" instead?

**Comment by afdaniele** [comment]
Fixed in https://github.com/afdaniele/x-docker/commit/00e33066476915a909f7f3ebf7c1b1a805869df9
